import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar-new"
import { CollapseSidebar } from "@/components/CollapseSidebar";
import { Header } from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    // <html lang="en">
    //   <body
       
    //   >
    //     <SidebarProvider>
    //     <AppSidebar />
        
    //     {/* <CollapseSidebar/> */}
        
    //     <main  >
        
    //     {children}
    //     </main>
    //      </SidebarProvider>
    //   </body>
    // </html>

    <html lang="en" >
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased ` }

    >
      <SidebarProvider>
        <AppSidebar />
        
        <main className="flex flex-col items-center justify-center min-h-screen w-full bg-gradient-to-b from-background via-sidebar/70 to-sidebar border">
        {/* <Header /> */}
          {children}
        </main>
      </SidebarProvider>
    </body>
  </html>
    
  );
}
